services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: /api
    restart: always
    ports:
      - '9000:9000'
    depends_on:
      - backend
  backend:
    build: ./backend
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CORS_ORIGIN: http://localhost:9000
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
  db:
    image: postgres:17.5-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db

volumes:
  postgres_data: