spring:
  application:
    name: infoCRM

  datasource:
    url: jdbc:postgresql://localhost/infocrm
    username: infocrm
    password: infocrm

  jackson:
    mapper:
      default-view-inclusion: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

security:
  jwt:
    expiration: 15m
    secret: 3d6f7f4db9a7ca65e6cbbd5c60a9b6f88e1e9b2a7b77b4a1e5e8e7f2c8e1e3d9
    token-name: token