spring:
  application:
    name: javaCRM
    version: 1.0.0

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jackson:
    mapper:
      default-view-inclusion: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: true

  liquibase:
    change-log: db/changelog/changelog-root.yaml
    enabled: true

cors:
  origin: ${CORS_ORIGIN:http://localhost:5173}

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 15m
    token-name: token
    refresh:
      expiration: 30d
      token-name: refresh

server:
  tomcat:
    max-swallow-size: -1